import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:uuid/uuid.dart';

import 'package:worxvisitorapp/core/constants/server_link.dart';
import 'package:worxvisitorapp/services/secure_storage_service.dart';
import 'package:worxvisitorapp/services/api_service.dart';

class AuthController extends ChangeNotifier {
  /// Callback when authentication is approved (navigate based on site count)
  final Future<void> Function() onApproved;

  AuthController({
    required this.onApproved,
  });

  //Existing Login 
  final bool _isCheckingInitialAuth = true;
  bool get isCheckingInitialAuth => _isCheckingInitialAuth;

  /// UUID generated by Flutter 
  String? _uuid;
  String? get uuid => _uuid;

  /// URL displayed inside QR
  String? _qrUrl;
  String? get qrUrl => _qrUrl;

  /// Polling variables
  Timer? _pollTimer;
  final bool _isPolling = false;
  bool get isPolling => _isPolling;

  /// Status message shown on UI
  String _statusMessage = 'Step 1: QR code generated. Please Scan.';
  String get statusMessage => _statusMessage;

  /// Whether we are currently polling authenticateDevice()
  bool _isPollingStarted = false;
  bool get isPollingStarted => _isPollingStarted;

  /// Error flag
  bool _hasError = false;
  bool get hasError => _hasError;

  ///Option 1. STEP 1 - Initial Auth Check (called by AuthPage)  Returns TRUE if authenticated, FALSE if not.
  //////   - true  -> already authenticated on this device 
  ///   - false -> no existing login
  Future<bool> checkExistingAuth() async {

    debugPrint('start finding the pre-authentication');
    try {
      final token = await SecureStorageService.getAuthToken();
      final alreadyAuthed = token != null && token.isNotEmpty;

      _hasError = false;
      _statusMessage = alreadyAuthed ? 'Already authenticated on this device.' : 'No existing login found. Please scan the QR code.';
      notifyListeners();
      return alreadyAuthed;
    } catch (e) {
      _hasError = true;
      _statusMessage = 'Error while checking existing login. Please start a new session.';
      notifyListeners();
      debugPrint('not pre-authentication found');
      return false;
    } 
  }

  //Option 2.1 Flutter create UUID and QR URL (also resets polling state)
  //This must only be called AFTER confirming the tablet is NOT authenticated.
  void generateLocalQr() {
    try {
      const uuidGen = Uuid();
      final newUuid = uuidGen.v4();

      _uuid = newUuid;
      _qrUrl = ServerLink.newSessionURL + newUuid;
      //print("QR URL code");
      //print(_qrUrl);

      _statusMessage = "Step 1: Please scan the QR code.";
      _hasError = false;
      notifyListeners();

    } catch (e) {
      debugPrint('Error generating QR: $e');
      _hasError = true;
      _statusMessage = "Failed to generate QR code, Please contact development team";
      notifyListeners();
    }
  }

  // STEP 2.2 - Start Polling Called when user taps "I have scanned the barcode"
  // Polling stops when:  ✔ Approved  ✖ Error ⏳ Timeout
  Future<void> startPolling() async {
    if (_uuid == null) {
      _hasError = true;
      _statusMessage = 'QR code is not ready. Please regenerate.';
      notifyListeners();
      return;
    }

    if (isPollingStarted) {
      // Already polling, ignore repeated taps
      return;
    }

    _isPollingStarted = true;
    _hasError = false;
    _statusMessage = 'Step 2: Waiting for login approval...';
    notifyListeners();

    const pollInterval = Duration(seconds: 3);
    const timeout = Duration(seconds: 60);
    final startTime = DateTime.now();

    while (true) {
      // 1. Timeout check
      final elapsed = DateTime.now().difference(startTime);
      if (elapsed >= timeout) {
        _isPollingStarted = false;
        _hasError = true;
        _statusMessage = 'Authentication timed out. Please restart QR login and try again.';
        notifyListeners();
        return;
      }

      try {
        // 2. Call backend with current setupCode(UUID)
        final data = await ApiService.authenticateDevice(setupCode: _uuid!);
        //print("return response from server");
        //print(data);
        // 3. If we get here, authenticateDevice returned 200 and data is valid.
        final token = data['access_token'] as String?;
        if (token == null || token.isEmpty) {
          throw Exception('Missing access_token in response.');
        }
        // 4. Save auth token & optional sites
        await SecureStorageService.saveAuthToken(token);

        //**** extract sites here, and same the data locally */

        _isPollingStarted = false;
        _hasError = false;
        _statusMessage = 'Authentication successful. Loading dashboard...';
        notifyListeners();

        debugPrint('Authentication success, token saved.');
        
        // 5. Navigate to index (dashboard/new-site)
        await onApproved();
        return;
      } catch (e) {
        // Here we treat all errors as "not ready yet" until timeout.
        // If you want to stop immediately for 401 (invalid code),
        // you can parse e.toString() and break earlier.
        debugPrint(' authenticateDevice error: $e');
      }

      // 6. Wait a bit before the next attempt
      await Future.delayed(pollInterval);
    }
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

}